# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq/ip/zynq_axi_interconnect_0_imp_auto_pc_0/zynq_axi_interconnect_0_imp_auto_pc_0.xci
# IP: The module: 'zynq_axi_interconnect_0_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.gen/sources_1/bd/zynq/ip/zynq_axi_interconnect_0_imp_auto_pc_0/zynq_axi_interconnect_0_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_interconnect_0_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq/ip/zynq_axi_interconnect_0_imp_auto_pc_0/zynq_axi_interconnect_0_imp_auto_pc_0.xci
# IP: The module: 'zynq_axi_interconnect_0_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.gen/sources_1/bd/zynq/ip/zynq_axi_interconnect_0_imp_auto_pc_0/zynq_axi_interconnect_0_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_interconnect_0_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
