# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq/ip/zynq_mips_core_0_0/zynq_mips_core_0_0.xci
# IP: The module: 'zynq_mips_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.gen/sources_1/bd/zynq/ip/zynq_mips_core_0_0/ip/fp_add/fp_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.gen/sources_1/bd/zynq/ip/zynq_mips_core_0_0/ip/fp_mul/fp_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_mul || ORIG_REF_NAME==fp_mul} -quiet] -quiet

# IP: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.srcs/sources_1/bd/zynq/ip/zynq_mips_core_0_0/zynq_mips_core_0_0.xci
# IP: The module: 'zynq_mips_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.gen/sources_1/bd/zynq/ip/zynq_mips_core_0_0/ip/fp_add/fp_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.gen/sources_1/bd/zynq/ip/zynq_mips_core_0_0/ip/fp_mul/fp_mul.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_mul || ORIG_REF_NAME==fp_mul} -quiet] -quiet
