# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq/zynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_interconnect_0_0/zynq_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_interconnect_0_0 || ORIG_REF_NAME==zynq_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_ahblite_bridge_0_0/zynq_axi_ahblite_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_ahblite_bridge_0_0 || ORIG_REF_NAME==zynq_axi_ahblite_bridge_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xlconstant_0_0/zynq_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_xlconstant_0_0 || ORIG_REF_NAME==zynq_xlconstant_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_proc_sys_reset_0_0/zynq_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_mips_core_0_0/zynq_mips_core_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_mips_core_0_0 || ORIG_REF_NAME==zynq_mips_core_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_interconnect_0_imp_auto_pc_0/zynq_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==zynq_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/user/Desktop/Work/CO_homework/LAB5-2/homework/vivado/zynq_system/zynq_system.gen/sources_1/bd/zynq/zynq_ooc.xdc
